# Generated by Django 6.0.6 on 2026-07-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='games/', verbose_name='photo'),
        ),
    ]
