# Generated by Django 6.0.6 on 2026-07-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_date_of_publication_alter_game_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Жанр'),
        ),
    ]
